services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.10
    restart: unless-stopped
    volumes:
      - ./influxdb:/var/lib/influxdb
        #- ./influxdb.conf:/etc/influxdb/influxdb.conf
        #- ./config:/etc/influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUX_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUX_PASS}

  grafana:
    restart: unless-stopped
    container_name: grafana
      #image: grafana/grafana:9.5.2-ubuntu
    image: grafana/grafana:9.4.10-ubuntu
    user: '472'
    volumes:
      - ./grafana/etc:/etc/grafana
      - ./grafana/storage:/var/lib/grafana
      - ./grafana/log:/var/log/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
  telegraf:

    restart: unless-stopped
    image: telegraf:1.26.3-alpine
    container_name: telegraf
    volumes:
      - ./telegraf:/etc/telegraf:ro
    depends_on:
      - influxdb
    command: --config-directory /etc/telegraf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: servers
