services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.10
    restart: unless-stopped
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    networks:
      - servers_net
#docker run -ti --rm  --user root --volume ./grafana/etc:/etc/grafana -v ./grafana/storage:/var/lib/grafana -v ./grafana/log:/var/log/grafana --entrypoint bash grafana/grafana:9.4.10-ubuntu
#chown -R root:root /etc/grafana
#chmod -R a+r /etc/grafana
#chown -R 472:472 /var/lib/grafana
  grafana:
    restart: unless-stopped
    container_name: grafana
      #image: grafana/grafana:9.5.2-ubuntu
      #image: grafana/grafana:9.4.10-ubuntu
    image: grafana/grafana:11.1.1-ubuntu
    user: '472'
    volumes:
      - ./grafana/etc:/etc/grafana
      - ./grafana/storage:/var/lib/grafana
      - ./grafana/log:/var/log/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
    depends_on:
      - influxdb
    networks:
      - servers_net
  telegraf:

    restart: unless-stopped
    image: telegraf:1.26.3-alpine
    container_name: telegraf
    volumes:
      - ./telegraf:/etc/telegraf:ro
    depends_on:
      - influxdb
    command: --config-directory /etc/telegraf
    networks:
      - servers_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  servers_net:
    external: true
